### ISSUE TITLE
incomplete refactoring

### ISSUE THREAD

**Issue by jbrucker** [SainTurDaY27/refactoring-practice#1]
https://github.com/SainTurDaY27/refactoring-practice/blob/26a4739c200173bf6af5bc91e7586466c77a4a72/recipe/main.py#L16-L34

you have unnecessary assignment of recipe attributes in main.
The main point of this refactoring is to eliminate that.

**Comment by SainTurDaY27** [comment]
Have fix on refactoring (eliminate unnecessary attributes).
